import Router from "express";
import login from "./login.js";
import homepage from "./homepage.js";
import signup from "./register.js";
import forgetpassword from "./forgetpassword";
import changepassword from "./changepassword";
import verifychangepassword from "./verifychangepassword";
import verifyemail from "./verifyemail";
import google from "./google";
import facebook from "./facebook";
const router = Router();
router.use("/", homepage);
router.use("/", login);
router.use("/", signup);
router.use("/signin", forgetpassword);
router.use("/signin", changepassword);
router.use("/signin/verifycode", verifychangepassword);
router.use("/signup/verifyemail", verifyemail);
router.use("/", google);
router.use("/", facebook);
export default router;
